version: '2'
services:
  server:
    image: node:12.18.4
    ports: 
      - 3000:3000
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm start"
  client:
    image: node:12.18.4
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    command: bash -c "npm install"
    depends_on:
      - server
